### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by UnityDev007** [guoxx/UnityDenoiserPlugin#3]
# OIDNDenoiser VRAM Leak Issue

The OIDNDenoiser implementation consistently results in a major VRAM leak due to improper resource management during the destruction of the OIDNDenoiser object.

EDIT: This issue is specific to OIDN; OptiX doesn't show a VRAM leak.

## Observation
Use the test the code below and observe the VRAM leak.

```csharp
using UnityEngine;

public class OIDNVramLeak : MonoBehaviour {    

    private UnityDenoiserPlugin.DenoiserPluginWrapper OIDNDenoiser;

    private void Start() {
        CreateDenoiser();
    }

    private void Update() {
        if (Input.GetKeyDown(KeyCode.Space)) {
            DestroyDenoiser();
            CreateDenoiser();
        }
    }

    private void CreateDenoiser() {
        UnityDenoiserPlugin.DenoiserConfig cfg = new UnityDenoiserPlugin.DenoiserConfig() {
            imageWidth = 2048,
            imageHeight = 2048,
            guideAlbedo = 1,
            guideNormal = 1,
            temporalMode = 0,
            cleanAux = 1,
            prefilterAux = 0
        };
        OIDNDenoiser = new UnityDenoiserPlugin.DenoiserPluginWrapper(UnityDenoiserPlugin.DenoiserType.OIDN, cfg);
        Debug.Log("OIDNDenoiser created.");
    }

    private void DestroyDenoiser() {
        if (OIDNDenoiser != null) {
            OIDNDenoiser.Dispose();
            OIDNDenoiser = null;
            Debug.Log("OIDNDenoiser destroyed.");
        }
    }
}

**Comment by guoxx** [comment]
Hi, thank you for reporting the memory leak issue. Which commit are you using? There's a known memory leak with the OIDN denoiser that was fixed in commit 718fe52. In the meantime, I will add more code to detect memory leaks.

**Comment by UnityDev007** [comment]
Hi, thanks for following up. I can confirm that the VRAM leak is still present in the latest commit (using the pre-compiled DLLs), occurring during the destruction of the OIDNDenoiser object.

**Comment by guoxx** [comment]
@UnityDev007 
OIDN memory leak is fixed in the latest commit 50e3e8e3. 
At the meantime, I've update OIDN to 2.3.1. Thank you very much for reporting this issue.
